In [2]:
from sklearn import svm,metrics
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import pandas as pd
import random

matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['font.size'] = 10
matplotlib.rcParams['axes.unicode_minus'] = False

In [4]:
df = pd.read_csv('../z20_data/02.iris.csv')
df.head(3)

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa

In [6]:
df.shape

(150, 5)

In [12]:
df.iloc[:,4:]

               Name
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [15]:
# 1. 데이터 전처리
# 데이터 분리 SepalLength,SepalWidth,PetalLength,PetalWidth/ Name
datas = df.iloc[:,:-1]
results = df.iloc[:,4:]

In [16]:
# train, test 데이터 분리 - 자동으로 랜덤으로 섞여 분리해줌
train_input,test_input,train_target, test_target = train_test_split(datas,results)

In [18]:
test_input

     SepalLength  SepalWidth  PetalLength  PetalWidth
29           4.7         3.2          1.6         0.2
122          7.7         2.8          6.7         2.0
107          7.3         2.9          6.3         1.8
41           4.5         2.3          1.3         0.3
61           5.9         3.0          4.2         1.5
91           6.1         3.0          4.6         1.4
70           5.9         3.2          4.8         1.8
71           6.1         2.8          4.0         1.3
11           4.8         3.4          1.6         0.2
127          6.1         3.0          4.9         1.8
2            4.7         3.2          1.3         0.2
8            4.4         2.9          1.4         0.2
103          6.3         2.9          5.6         1.8
45           4.8         3.0          1.4         0.3
58           6.6         2.9          4.6         1.3
84           5.4         3.0          4.5         1.5
79           5.7         2.6          3.5         1.0
13           4.3         3.0          1.1         0.1
36           5.5         3.5          1.3         0.2
89           5.5         2.5          4.0         1.3
112          6.8         3.0          5.5         2.1
104          6.5         3.0          5.8         2.2
76           6.8         2.8          4.8         1.4
72           6.3         2.5          4.9         1.5
93           5.0         2.3          3.3         1.0
146          6.3         2.5          5.0         1.9
64           5.6         2.9          3.6         1.3
22           4.6         3.6          1.0         0.2
145          6.7         3.0          5.2         2.3
95           5.7         3.0          4.2         1.2
23           5.1         3.3          1.7         0.5
4            5.0         3.6          1.4         0.2
118          7.7         2.6          6.9         2.3
97           6.2         2.9          4.3         1.3
44           5.1         3.8          1.9         0.4
115          6.4         3.2          5.3         2.3
96           5.7         2.9          4.2         1.3
140          6.7         3.1          5.6         2.4

In [19]:
# 2.데이터 학습시키기
clf = svm.SVC()
clf.fit(train_input, train_target)

# 3. 데이터 예측하기
pre = clf.predict(test_input)
print("test질문의 답 : ",pre)

test질문의 답 :  ['Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica']

c:\Python312\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [21]:
len(test_input)

38

In [20]:
# 정답률 구하기
score = clf.score(test_input,test_target)
print("정답률 : ",score)

정답률 :  0.9736842105263158

In [35]:
# 4.9, 2.9, 1.4 0.2 무슨 품종?
# 5.6 3 4.1 1.2 
# 6.5 2.8 6.7 2.2
data1 = [4.9, 2.9, 1.4, 0.2]
data2 = [5.6, 3, 4.1 ,1.2 ]
data3 = [6.5 ,2.8, 6.7, 2.2]
data4 = [data1, data2, data3]

In [31]:
input1 = input("데이터를 입력하세요")
print(input1)
input_arr = input1.split(',')
print(input_arr)

5.6, 3, 4.1, 1.2
['5.6', ' 3', ' 4.1', ' 1.2']

In [36]:
pre = clf.predict(data4) # 리스트 안에 리스트 형태여야 함 [data1:리스트]:리스트 data4:[[]]인 상태
print("test질문의 답 : ",pre)

test질문의 답 :  ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

c:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(